version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: get_it_done_db
    volumes:
      - pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432

volumes:
  pgdata:
